steps:
# build the docker images and store in container registry in github.com folder
- name: 'gcr.io/cloud-builders/docker' # it is inbuilt images and below tasks run on this images/instance
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp:latest', '-t', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/myapp:$BUILD_ID', '.' ]
  id: 'build-myapp-image'
  waitFor: ['-'] 
